name: buildenvs/base-golang

on:
  push:
    branches: [stable]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [staging]
    paths:
      - 'buildenvs/qemu.Dockerfile'
      - 'buildenvs/base.Dockerfile'
      - 'buildenvs/base-golang.Dockerfile'
      - '.github/workflows/base-golang.yaml'
  workflow_dispatch:

env:
  QEMU_VERSION: 7.2.4

jobs:
  qemu:
    runs-on: nscloud-ubuntu-22.04-amd64-8x16

    steps:
      - uses: namespacelabs/nscloud-setup@v0
        id: nsc

      - name: Build OCI image
        uses: docker/build-push-action@v5
        with:
          file: ./buildenvs/qemu.Dockerfile
          tags: ${{ steps.nsc.outputs.registry-address }}/kraftkit.sh/qemu:${{ env.QEMU_VERSION }}
          platforms: linux/amd64
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  myself:
    runs-on: nscloud-ubuntu-22.04-amd64-8x16
    steps:
      - uses: namespacelabs/nscloud-setup@v0
        id: nsc

      - name: Build OCI image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./buildenvs/myself.Dockerfile
          tags: ${{ steps.nsc.outputs.registry-address }}/kraftkit.sh/myself:latest
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  base:
    runs-on: nscloud-ubuntu-22.04-amd64-8x16
    needs: [qemu, myself]

    steps:
      - uses: namespacelabs/nscloud-setup@v0
        id: nsc

      - name: Build OCI image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./buildenvs/base.Dockerfile
          tags: ${{ steps.nsc.outputs.registry-address }}/kraftkit.sh/base:latest
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  base-golang:
    runs-on: nscloud-ubuntu-22.04-amd64-8x16
    needs: [base]
    steps:
      - uses: namespacelabs/nscloud-setup@v0
        id: nsc

      - name: Build OCI image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./buildenvs/base-golang.Dockerfile
          tags: ${{ steps.nsc.outputs.registry-address }}/kraftkit.sh/base-golang:latest
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}