name: github-action

on:
  push:
    branches: [stable]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [staging]
    paths:
      - 'action.yml'
      - 'tools/github-action/**'
      - 'buildenvs/github-action.Dockerfile'
      - 'buildenvs/qemu.Dockerfile'
      - 'buildenvs/base.Dockerfile'
      - '.github/workflows/github-action.yaml'
  workflow_dispatch:

env:
  QEMU_VERSION: 7.2.4

jobs:
  qemu:
    runs-on: 
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-tag-unikraft-qemu
      - nscloud-cache-size-100gb
      - nscloud-exp-container-image-cache

    steps:
      - uses: namespacelabs/nscloud-setup@v0
        id: nsc

      - name: Build OCI image
        uses: docker/build-push-action@v5
        with:
          file: ./buildenvs/qemu.Dockerfile
          tags: ${{ steps.nsc.outputs.registry-address }}/kraftkit.sh/qemu:${{ env.QEMU_VERSION }}
          platforms: linux/amd64
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  github-action:
    runs-on: 
      - nscloud-ubuntu-22.04-amd64-8x16-with-cache
      - nscloud-cache-tag-unikraft-qemu
      - nscloud-cache-size-100gb
      - nscloud-exp-container-image-cache
    needs: [qemu]

    steps:
      - uses: actions/checkout@v4

      - uses: namespacelabs/nscloud-setup@v0
        id: nsc

      - name: Pull qemu image
        run: |
          docker pull ${{ steps.nsc.outputs.registry-address }}/kraftkit.sh/qemu:${{ env.QEMU_VERSION }}

      - name: Build OCI Image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: kraftkit.sh/github-action:v0
          platforms: linux/amd64
          file: ./buildenvs/github-action.Dockerfile
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Fetch helloworld
        uses: actions/checkout@v4
        if: ${{ github.event_name != 'push' }}
        with:
          repository: unikraft/app-helloworld
          fetch-depth: 1
          path: _helloworld

      - name: Integration test
        uses: ./
        if: ${{ github.event_name != 'push' }}
        with:
          loglevel: debug
          workdir: _helloworld
          arch: x86_64
          plat: qemu
          name: helloworld
          execute: true

      - name: Push OCI Image
        uses: docker/build-push-action@v5
        if: ${{ github.event_name == 'push' }}
        with:
          push: true
          tags: ${{ steps.nsc.outputs.registry-address }}/kraftkit.sh/github-action:v0
          platforms: linux/amd64
          file: ./buildenvs/github-action.Dockerfile
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
